boot.o: boot.S multiboot.h x86_desc.h types.h
irq.o: irq.S x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
exceptions.o: exceptions.c exceptions.h lib.h types.h
file_system.o: file_system.c file_system.h lib.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h exceptions.h x86_desc.h types.h irq.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h rtc.h \
  debug.h tests.h idt.h paging.h keyboard.h file_system.h syscall.h pit.h \
  mouse.h malloc.h
keyboard.o: keyboard.c keyboard.h types.h lib.h i8259.h syscall.h \
  paging.h
lib.o: lib.c lib.h types.h
malloc.o: malloc.c malloc.h types.h lib.h
mouse.o: mouse.c mouse.h lib.h types.h i8259.h
paging.o: paging.c x86_desc.h types.h paging.h
pit.o: pit.c pit.h types.h lib.h i8259.h syscall.h
rtc.o: rtc.c rtc.h types.h lib.h i8259.h
syscall.o: syscall.c lib.h types.h paging.h syscall.h x86_desc.h \
  file_system.h rtc.h keyboard.h
tests.o: tests.c tests.h x86_desc.h types.h paging.h lib.h keyboard.h \
  rtc.h file_system.h syscall.h malloc.h
